name: Docker Image Build

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'JMusicBot version'     
        required: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        build-args: |
          BUILD_DATE=${{ steps.date.outputs.date }}
          VCS_REF=${{ steps.vcs_ref.outputs.vcs_ref }}
          VERSION=${{ inputs.version }}
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/jmusicbot:${{ inputs.version }}
          ${{ secrets.DOCKER_USERNAME }}/jmusicbot:latest

    - name: Set BUILD_DATE
      id: date
      run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

    - name: Set VCS_REF
      id: vcs_ref
      run: echo "::set-output name=vcs_ref::$(git rev-parse --short HEAD)"

